nome = input(' Digite seu nome: ')
print('Prazer em te conhecer {:50}!'.format(nome))
print('Prazer em te conhecer {:>50}!'.format(nome))
print('Prazer em te conhecer {:<50}!'.format(nome))
print('Prazer em te conhecer {:^50}!'.format(nome))
print('Prazer em te conhecer {:*^50}!'.format(nome))
