n = input ('Digite um caracter qualquer: ')
print('O tipo primitivo desse valor é: {}'.format(type(n)))
print('Você só digitou um espaço vazio? {}'.format(n.isspace()))
print(f'Você digitou um número? {n.isnumeric()}')
print('Você digitou uma palavra?', n.isalpha())
print('Você digitou algo alfanumérico?', n.isalnum())
print('Está toda a palavra em maiúsculo?', n.isupper())
print('Está toda a palavra em minúsculo?', n.islower())
print('Está capitalizada?', n.istitle())
